version: "3.8"
services:
  bancodados:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=value
    ports: 
      - 2020:5432
    networks:
      - aplicacao-vitima

  aplicacaovitima:
    image: rp4/vitima:latest
    environment:
      - DATABASE_URL=postgresql://postgres:value@bancodados:5432/vitima?schema=public
    ports: 
      - 3333:3333 
    networks:
      - aplicacao-vitima
networks:
  aplicacao-vitima:
